AWSTemplateFormatVersion: "2010-09-09"
Description: Jupyter Executor Service.
Parameters:
  LambdaFuncName:
    Type: String
    Default: "pythonTest"
  LambdaRuntime:
    Type: String
    Default: "python3.7"
  LambdaHandler:
    Type: String
    Default: "index.handler"
  LambdaMemory:
    Type: Number
    Default: 128
  LambdaTimeout:
    Type: Number
    Default: 40
Resources:
  LambdaFunc:
    Properties:
      CodeUri: s3://<bucket-name>/<key>
      Description: Vue Testing Suite
      FunctionName:
        Ref: "LambdaFuncName"
      Events:
        ExecuteFunc:
          Properties:
            Method: any
            Path: /
          Type: Api
      Handler:
        Ref: "LambdaHandler"
      MemorySize:
        Ref: "LambdaMemory"
      Runtime:
        Ref: "LambdaRuntime"
      Timeout:
        Ref: "LambdaTimeout"
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
